// Generates src/version.ts from package.json so the SDK can self-report its
// name/version without a hand-maintained copy that can drift out of sync.
// Runs automatically before `build`/`dev` (see package.json scripts).
const fs = require('fs');
const path = require('path');

const pkg = require('../package.json');
const out = `// Generated by scripts/generate-version.js from package.json — do not edit.
export const SDK_NAME = ${JSON.stringify(pkg.name)};
export const SDK_VERSION = ${JSON.stringify(pkg.version)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'version.ts'), out);
